### PR TITLE
Project Twitter Clone - Arturo

### PR DESCRIPTION
**Pull request by scorpiocavalier**

### CODE REVIEW

**Review by thedanamo — CHANGES_REQUESTED** [review]
Good so far. Missing the posting tweet function, Can you add that?

**Comment by scorpiocavalier** [comment]
Will work on it Sunday

**Review by thedanamo — APPROVED** [review]
Accepted. It should make a fetch to the server at least...

**Comment by scorpiocavalier** [comment]
I was gonna continue working on it today

**Pull request closed without merging**
